### ISSUE TITLE
Add dev dependency badge

### ISSUE THREAD

**Issue by joshghent** [joshghent/color-formatter#3]
https://david-dm.org/

**Comment by hiteshpr** [comment]
I can work on this.

**Comment by joshghent** [comment]
@hiteshpr Great stuff! All yours! Thanks for offering to help 👍

**Comment by hiteshpr** [comment]
@joshghent What exactly is needed here?

**Comment by joshghent** [comment]
@hiteshpr Basically you need to follow the instructions on that website and add the dev dependencies badge to the Readme near the top
